openapi: 3.0.0
security:
  - regularSecurity: []
    OAuth2:
      - readOnly
info:
  title: Team API
  description: API to retrieve information about team members
  version: 1.0.0
servers:
  - url: https://api.womencodingcommunity.com/v1/cms
  - url: http://localhost:8080/v1.cms
paths:
  /teams:
    get:
      summary: Get all team members
      security:
        - OAuth2:
            - write
            - read
        - apiKey: []
      
      responses:
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404'
        "406":
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/406'
        "429":
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/429'

        '200':
          description: A list of team members
          content:
            application/json:
              schema:
                type: array
                maxItems: 30
                items:
                  $ref: '#/components/schemas/TeamMember'
              examples:
                example1: 
                  value:
                    - title: Meet our team
                      subtitle: Core Team
                      description: The core team of our community is composed of visionary directors and dynamic leaders, who bring a wealth of experience and dedication to empowering women in technology.
                      members: 
                        - name: Irina Kamalova
                          memberType: WCC Director
                          position: Senior Software Engineer
                          image: https://womencodingcommunity.com/assets/images/team/8.jpeg
                          network:
                            - name: Linkedin
                              link: https://www.linkedin.com/in/irina-kamalova/
                            - name: Medium
                              link: https://iren-kamalova.medium.com/
                        - name: Eleonora Belova
                          memberType: WCC Lead
                          position: Test Automation Engineer
                          image: https://womencodingcommunity.com/assets/images/team/7.jpeg
                          network:
                            - name: Linkedin
                              link: https://www.linkedin.com/in/eleonora-belova-7069baa5/
                            - name: Github
                              link: https://github.com/nora-weisser/

        default:
          description: Default
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'

components: 
  
  securitySchemes:
    regularSecurity:
      type: http
      scheme: basic
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            readOnly: read objects in your account
          authorizationUrl: https://womencodingcommunity.com/oauth/authorize # TBD
          tokenUrl: https://womencodingcommunity.com/oauth/token # TBD

  schemas:
    
    401: 
      description: Unauthorized
      type: object
      additionalProperties: false
      properties:
        message:
          type: string
          maxLength: 30
          example: Unauthorized
    404: 
      description: Not Found
      type: object
      additionalProperties: false
      properties:
        message:
          type: string
          maxLength: 30
          example: Not Found
    403: 
      description: Forbidden
      type: object
      additionalProperties: false
      properties:
        message:
          type: string
          maxLength: 30
          example: Forbidden
    406: 
      description: Not Acceptable
      type: object
      additionalProperties: false
      properties:
        message:
          type: string
          maxLength: 30
          example: Not Acceptable
    429: 
      description: Too Many Requests
      type: object
      additionalProperties: false
      properties:
        message:
          type: string
          maxLength: 30
          example: Too Many Requests

    TeamPage:
      type: object
      required:
        - title
        - subtitle
        - description
      additionalProperties: false
      properties:
        title:
          type: string
          maxLength: 30
          example: Meet our team
        subtitle:
          type: string
          maxLength: 80
          example: Core team
        description:
          type: string
          maxLength: 500
          example: The core team of our community is composed of visionary directors and dynamic leaders, who bring a wealth of experience and dedication to empowering women in technology. These esteemed professionals are committed to fostering an environment of growth, inclusivity and support, guiding our community toward achieving its mission and goals.
        members:
          type: array
          maxItems: 30
          items:
            $ref: '#/components/schemas/TeamMember'
          
    TeamMember:
      type: object
      required:
        - name
        - position
        - memberType
        - image
      additionalProperties: false
      properties:
        name:
          type: string
          maxLength: 30
          example: Irina Kamalova
        position:
          description: Professional experience
          type: string
          maxLength: 30
          example: Senior Software Engineer
        memberType:
          $ref: '#/components/schemas/MemberType'
        image:
          description: Path of member profile image
          type: string
          maxLength: 100
          pattern: ^(\/?[\w\-.]+\/)*[\w\-.]+\.\w+$
          example: WCC Director
        network:
          type: array
          maxItems: 5
          items:
            $ref: '#/components/schemas/SocialNetwork'
    
    SocialNetwork:
      type: object
      required:
        - name
        - link
      additionalProperties: false
      properties:
        name:
          $ref: '#/components/schemas/SocialNetworkType'
          example: Linkedin
        link:
          type: string
          pattern: '^(https?|http):\/\/[^\s\/$.?#].[^\s]*$'
          example: https://www.linkedin.com/in/irina-kamalova


    SocialNetworkType:
      type: string
      enum:
        - Youtube
        - Github
        - Linkedin
        - Instagram
        - Facebook
        - Twitter
        - Medium
        - Slack
        - Meetup

    MemberType:
      type: string
      enum:
        - WCC Director
        - WCC Leader
        - Mentor
        - Mentee
        - Volunteer
        - Member
