openapi: 3.0.0

info:
  title: Session "About" APIs
  description: API to retrieve information about team members
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/cms/v1
  - url: https://wcc-cms.fly.dev/api/cms/v1

paths:
  /team:
    get:
      summary: Get team members grouped by MemberType
      parameters:
        - in: query
          name: memberType
          schema:
            type: string
            maxLength: 30
            pattern: '^[A-Z][a-z ]{0,30}$'
            example: Lead
          required: false
          description: Filter team members by their MemberType, in case it is empty return all types
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 1
            format: int32
          required: false
          description: Page number for pagination
        - in: query
          name: pageSize
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 25
            format: int32
          required: false
          description: Number of items per page
      security:
        - apiKey: [ ]
      responses:
        '200':
          description: List the content of Team's Page with pagination
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamPagePaginated'
        '401':
          $ref: 'schemas/responses.yml#/components/responses/Unauthorized'
        '403':
          $ref: 'schemas/responses.yml#/components/responses/Forbidden'
        '404':
          $ref: 'schemas/responses.yml#/components/responses/NotFound'
        '406':
          $ref: 'schemas/responses.yml#/components/responses/NotAcceptable'
        '429':
          $ref: 'schemas/responses.yml#/components/responses/TooManyRequests'
        '5XX':
          $ref: 'schemas/responses.yml#/components/responses/UnexpectedError'

        default:
          $ref: 'schemas/responses.yml#/components/responses/Forbidden'

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    TeamPagePaginated:
      type: object
      required:
        - data
        - metadata
      additionalProperties: false
      properties:
        data:
          $ref: 'schemas/modules.yml#/components/schemas/MemberPage'
        metadata:
          $ref: 'schemas/responses.yml#/components/schemas/Metadata'

security:
  - apiKey: [ ]