openapi: 3.0.0

info:
  title: Session "Events Page" APIs
  description: API to retrieve information about events
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/cms/v1
  - url: https://wcc-cms.fly.dev/api/cms/v1
paths:
    get:
      summary: Get Events Page contents
      security:
        - apiKey: [ ]
      parameters: []
      responses:
        "200":
          description: List of Events
          content:
            application/json:
              schema:


                '401':
                  $ref: 'schemas/responses.yml#/components/responses/Unauthorized'
                '403':
                  $ref: 'schemas/responses.yml#/components/responses/Forbidden'
                '404':
                  $ref: 'schemas/responses.yml#/components/responses/NotFound'
                '406':
                  $ref: 'schemas/responses.yml#/components/responses/NotAcceptable'
                '429':
                  $ref: 'schemas/responses.yml#/components/responses/TooManyRequests'
                '5XX':
                  $ref: 'schemas/responses.yml#/components/responses/UnexpectedError'

                default:
                  $ref: 'schemas/responses.yml#/components/responses/Forbidden'

    components:
      securitySchemes:
        apiKey:
          type: apiKey
          in: header
          name: X-API-Key
      schemas:
        EventPage:
          type: object
          properties:
            heroSection:
              $ref: '#/components/schemas/HeroSection'
            pageIntroSection:
              $ref: '#/components/schemas/PageIntroSection'
            eventsSearchSection:
              $ref: '#/components/schemas/EventSearchSection'




        PageIntroSection:
                type: object
                properties:
                  paragraph:
                    type: string
                    example: |
                      Join the Women Coding Community for events and meetups that enhance your skills, deepen your knowledge, and expand your professional network.
                      Our events include webinars, hands-on workshops, study groups, panel discussions, and keynotes with industry experts.
                      Whether online or in-person, these gatherings offer valuable opportunities to share insights, learn collaboratively, and stay updated on the latest trends. Connect, grow, and thrive with fellow members in a supportive environment.


        EventsSearchSection:
          type: object
          properties:
            title:
              type: string
              example: "Events"
              maxLength: 50 #-- to decide together
              description:
                type: string
                example: "Events"
            navbar:
              type: object
              properties:
                - upcomingEvents:
                  $ref: 'schemas/attributes.yml#/components/schemas/attributes/Link'
                  description: Link for upcoming events
                - pastEvents:
                  $ref: 'schemas/attributes.yml#/components/schemas/attributes/Link'
                  description: Link for past events

              filterComponent:
                type: object

              searchListing:
                type: object
                properties:
                - categoryTag:
                    type: string
                    description: book club
                - eventDateTime:
                   type: string
                   example: THU, MAY 30, 2024, 8:00 PM to 9:30 PM CEST
                - eventTitle:
                    type: string
                - eventHost:
                    type: string
                    example: Jane Doe
                - eventDescription:
                    type: object
                    properties:
                      paragraph:
                      type: string
                      example: |
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                - link:
                      $ref: 'schemas/attributes.yml#/components/schemas/attributes/Link'
                      description: "Meetup link"
                - eventResources:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Event Resources:"
                        $ref: 'schemas/attributes.yml#/components/schemas/attributes/Link'
                        description: "Slides link"
                        $ref: 'schemas/attributes.yml#/components/schemas/attributes/Link'
                        description: "Recording link"

























