components:
    regularSecurity:
      type: http
      scheme: basic
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            readOnly: read objects in your account
          authorizationUrl: https://womencodingcommunity.com/oauth/authorize # TBD
          tokenUrl: https://womencodingcommunity.com/oauth/token # TBD